#!/sbin/openrc-run

NAME=${SVCNAME##*.}
if [ -n "${NAME}" -a "${SVCNAME}" != "influxdb" ]; then
    PID="/run/influxdb.${NAME}.pid"
    PNAME=$(echo ${RC_SVCNAME} | sed 's/\..*//g')
    CONF_DEFAULT="/etc/conf.d/influxdb.${NAME}"
else
    PID="/run/influxdb.pid"
    PNAME=${RC_SVCNAME}
    CONF_DEFAULT="/etc/conf.d/influxdb"
fi
CONF=${CONF:-${CONF_DEFAULT}}
EXEC=${EXEC:-/usr/bin/influxd}

depend() {
	need net
	provide influxdb
}

start() {
	ebegin "Starting influxdb"
	start-stop-daemon -q -b -S -u ${USER} -g ${GROUP} -m -p ${PID} -x ${EXEC} -2 ${LOG} -- ${OPTS} ${CONFIG}
	eend $?
}

stop() {
	ebegin "Stopping influxdb"
	start-stop-daemon --stop --quiet --pidfile ${PID}
	rm -f ${PID}
	eend $?
}
