<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
require_once 'Fedora/Autoloader'.'/autoload.php';

\Fedora\Autoloader\Autoload::addClassMap(
    array(
        'hamcrest\\arrays\\isarray' => '/Hamcrest/Arrays/IsArray.php',
                'hamcrest\\arrays\\isarraycontaining' => '/Hamcrest/Arrays/IsArrayContaining.php',
                'hamcrest\\arrays\\isarraycontaininginanyorder' => '/Hamcrest/Arrays/IsArrayContainingInAnyOrder.php',
                'hamcrest\\arrays\\isarraycontaininginorder' => '/Hamcrest/Arrays/IsArrayContainingInOrder.php',
                'hamcrest\\arrays\\isarraycontainingkey' => '/Hamcrest/Arrays/IsArrayContainingKey.php',
                'hamcrest\\arrays\\isarraycontainingkeyvaluepair' => '/Hamcrest/Arrays/IsArrayContainingKeyValuePair.php',
                'hamcrest\\arrays\\isarraywithsize' => '/Hamcrest/Arrays/IsArrayWithSize.php',
                'hamcrest\\arrays\\matchingonce' => '/Hamcrest/Arrays/MatchingOnce.php',
                'hamcrest\\arrays\\seriesmatchingonce' => '/Hamcrest/Arrays/SeriesMatchingOnce.php',
                'hamcrest\\assertionerror' => '/Hamcrest/AssertionError.php',
                'hamcrest\\basedescription' => '/Hamcrest/BaseDescription.php',
                'hamcrest\\basematcher' => '/Hamcrest/BaseMatcher.php',
                'hamcrest\\collection\\isemptytraversable' => '/Hamcrest/Collection/IsEmptyTraversable.php',
                'hamcrest\\collection\\istraversablewithsize' => '/Hamcrest/Collection/IsTraversableWithSize.php',
                'hamcrest\\core\\allof' => '/Hamcrest/Core/AllOf.php',
                'hamcrest\\core\\anyof' => '/Hamcrest/Core/AnyOf.php',
                'hamcrest\\core\\combinablematcher' => '/Hamcrest/Core/CombinableMatcher.php',
                'hamcrest\\core\\describedas' => '/Hamcrest/Core/DescribedAs.php',
                'hamcrest\\core\\every' => '/Hamcrest/Core/Every.php',
                'hamcrest\\core\\hastostring' => '/Hamcrest/Core/HasToString.php',
                'hamcrest\\core\\is' => '/Hamcrest/Core/Is.php',
                'hamcrest\\core\\isanything' => '/Hamcrest/Core/IsAnything.php',
                'hamcrest\\core\\iscollectioncontaining' => '/Hamcrest/Core/IsCollectionContaining.php',
                'hamcrest\\core\\isequal' => '/Hamcrest/Core/IsEqual.php',
                'hamcrest\\core\\isidentical' => '/Hamcrest/Core/IsIdentical.php',
                'hamcrest\\core\\isinstanceof' => '/Hamcrest/Core/IsInstanceOf.php',
                'hamcrest\\core\\isnot' => '/Hamcrest/Core/IsNot.php',
                'hamcrest\\core\\isnull' => '/Hamcrest/Core/IsNull.php',
                'hamcrest\\core\\issame' => '/Hamcrest/Core/IsSame.php',
                'hamcrest\\core\\istypeof' => '/Hamcrest/Core/IsTypeOf.php',
                'hamcrest\\core\\set' => '/Hamcrest/Core/Set.php',
                'hamcrest\\core\\shortcutcombination' => '/Hamcrest/Core/ShortcutCombination.php',
                'hamcrest\\description' => '/Hamcrest/Description.php',
                'hamcrest\\diagnosingmatcher' => '/Hamcrest/DiagnosingMatcher.php',
                'hamcrest\\featurematcher' => '/Hamcrest/FeatureMatcher.php',
                'hamcrest\\internal\\selfdescribingvalue' => '/Hamcrest/Internal/SelfDescribingValue.php',
                'hamcrest\\matcher' => '/Hamcrest/Matcher.php',
                'hamcrest\\matcherassert' => '/Hamcrest/MatcherAssert.php',
                'hamcrest\\matchers' => '/Hamcrest/Matchers.php',
                'hamcrest\\nulldescription' => '/Hamcrest/NullDescription.php',
                'hamcrest\\number\\iscloseto' => '/Hamcrest/Number/IsCloseTo.php',
                'hamcrest\\number\\orderingcomparison' => '/Hamcrest/Number/OrderingComparison.php',
                'hamcrest\\selfdescribing' => '/Hamcrest/SelfDescribing.php',
                'hamcrest\\stringdescription' => '/Hamcrest/StringDescription.php',
                'hamcrest\\text\\isemptystring' => '/Hamcrest/Text/IsEmptyString.php',
                'hamcrest\\text\\isequalignoringcase' => '/Hamcrest/Text/IsEqualIgnoringCase.php',
                'hamcrest\\text\\isequalignoringwhitespace' => '/Hamcrest/Text/IsEqualIgnoringWhiteSpace.php',
                'hamcrest\\text\\matchespattern' => '/Hamcrest/Text/MatchesPattern.php',
                'hamcrest\\text\\stringcontains' => '/Hamcrest/Text/StringContains.php',
                'hamcrest\\text\\stringcontainsignoringcase' => '/Hamcrest/Text/StringContainsIgnoringCase.php',
                'hamcrest\\text\\stringcontainsinorder' => '/Hamcrest/Text/StringContainsInOrder.php',
                'hamcrest\\text\\stringendswith' => '/Hamcrest/Text/StringEndsWith.php',
                'hamcrest\\text\\stringstartswith' => '/Hamcrest/Text/StringStartsWith.php',
                'hamcrest\\text\\substringmatcher' => '/Hamcrest/Text/SubstringMatcher.php',
                'hamcrest\\type\\isarray' => '/Hamcrest/Type/IsArray.php',
                'hamcrest\\type\\isboolean' => '/Hamcrest/Type/IsBoolean.php',
                'hamcrest\\type\\iscallable' => '/Hamcrest/Type/IsCallable.php',
                'hamcrest\\type\\isdouble' => '/Hamcrest/Type/IsDouble.php',
                'hamcrest\\type\\isinteger' => '/Hamcrest/Type/IsInteger.php',
                'hamcrest\\type\\isnumeric' => '/Hamcrest/Type/IsNumeric.php',
                'hamcrest\\type\\isobject' => '/Hamcrest/Type/IsObject.php',
                'hamcrest\\type\\isresource' => '/Hamcrest/Type/IsResource.php',
                'hamcrest\\type\\isscalar' => '/Hamcrest/Type/IsScalar.php',
                'hamcrest\\type\\isstring' => '/Hamcrest/Type/IsString.php',
                'hamcrest\\typesafediagnosingmatcher' => '/Hamcrest/TypeSafeDiagnosingMatcher.php',
                'hamcrest\\typesafematcher' => '/Hamcrest/TypeSafeMatcher.php',
                'hamcrest\\util' => '/Hamcrest/Util.php',
                'hamcrest\\xml\\hasxpath' => '/Hamcrest/Xml/HasXPath.php',
    ),
    __DIR__
);
// @codeCoverageIgnoreEnd
