#!/sbin/runscript
# GitLab 6.2 init script for Gentoo Linux
# see https://github.com/gitlabhq/gitlabhq/blob/master/doc/installation.md

PID="/run/gitlab-git-http-server.pid"

depend() {
	provide gitlab-git-http-server
}

start() {
	ebegin "Starting gitlab git http server"
	start-stop-daemon --start --background --make-pidfile --user ${GITLAB_USER} --pidfile ${PID} --exec /usr/bin/gitlab-git-http-server -- ${OPTS} ${REPOSITORIES}
	eend $?
}

stop() {
	ebegin "Stopping gitlab git http server"
	start-stop-daemon --stop --user ${GITLAB_USER} --pidfile ${PID}
	rm -f ${PID}
	eend $?
}
