#!/sbin/openrc-run
# Copyright 1999-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

command="/usr/bin/gitlab-workhorse"
command_args="${WORKHORSE_OPTS}"
command_background="yes"
command_user="${USER:-gitlab-workhorse}:${GROUP:-gitlab}"
description="GitLab Workhorse"
name="Gitlab Workhorse"
pidfile="/run/gitlab-workhorse/${RC_SVCNAME}.pid"

depend() {
	need net
}
