#!/sbin/openrc-run
# Copyright 1999-2018 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

command="/usr/bin/redir"
command_args="${OPTS}"
description="TCP port redirector"
name="TCP port redirector"
user="${REDIR_USER:-redir}"
group="${REDIR_GROUP:-redir}"
pidfile="/run/redir/${RC_SVCNAME}.pid"

depend() {
	need net
}

start_post() {
	pgrep -n "${RC_SVCNAME%%.*}" > "${pidfile}"
}
