#!/sbin/openrc-run
# Copyright 1999-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

command="/usr/bin/semaphore"
command_background="yes"
name="Semaphore"
description="Semaphore"
command_user="${SEMAPHORE_USER:-semaphore}:${SEMAPHORE_GROUP:-semaphore}"
pidfile="/run/${RC_SVCNAME}.pid"
config="${CONFIG:-/etc/semaphore/config.json}"
command_args="--config $config ${SEMAPHORE_OPTS}"

depend() {
	need net
}
