#!/sbin/openrc-run
# Copyright 1999-2023 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

command="/usr/bin/gitaly"
command_args="${GITALY_OPTS}"
command_background="yes"
command_user="${USER:-gitlab-gitaly}:${GROUP:-gitlab}"
description="GitLab Gitaly"
name="Gitlab Gitaly"
pidfile="/run/gitlab-gitaly/${RC_SVCNAME}.pid"
start_stop_daemon_args=" \
	--stdout /var/log/${RC_SVCNAME}/${RC_SVCNAME}.log \
	--stderr /var/log/${RC_SVCNAME}/${RC_SVCNAME}.log"

depend() {
	need net
}

start_post() {
	# Until gitaly will do it itself
	ewaitfile 5 /run/gitlab-gitaly/gitlab-gitaly.socket
	chmod g+w /run/gitlab-gitaly/gitlab-gitaly.socket
}
