#!/sbin/openrc-run
# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

command="${JAVA_HOME:-/usr/bin/java}"
command_args="-jar /usr/lib/unifi/lib/ace.jar start"
command_background="true"
command_user="${USER:-unifi}:${GROUP:-unifi}"
description="UniFi Controller"
name="UniFi Controller"
pidfile="/run/${RC_SVCNAME}.pid"
retry="20"

depend() {
	need net
}
