#!/sbin/openrc-run
# Copyright 1999-2018 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

command="/usr/bin/samplicate"
command_args="${OPTS} ${CONFIG}"
command_background="yes"
description="UDP packets forwarder"
name="UDP packets forwarder"
pidfile="/run/${RC_SVCNAME}.pid"

depend() {
	need net
}

start_post() {
	NAME=$(echo "$RC_SVCNAME" | sed 's/or/e/')
	pgrep -n "${NAME%%.*}" > "${pidfile}"
}
