#!/sbin/openrc-run
# Copyright 1999-2018 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

command="/usr/bin/nginx-amplify-agent.py"
name="NGINX Amplify Agent"
description="NGINX Amplify Agent"
user="${USER:-nginx}"
pidfile="/run/amplify-agent/amplify-agent.pid"
config=${CONFIG:-/etc/amplify-agent/agent.conf}
start_stop_daemon_args="start -q -- --config $config --pid $pidfile"
extra_commands="configtest"
description_configtest="Checks amplify-agent configuration"

depend() {
	need net
	use nginx dns
}

configtest() {
	$command configtest --config "$config"
}
