#!/sbin/openrc-run
# Copyright 1999-2018 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

command="/usr/sbin/rpc.rstatd"
command_args="$INTERFACE"
command_background="true"
name="Performance Metrics Gatherer"
description="Performance Metrics Gatherer"
pidfile="/run/${RC_SVCNAME}.pid"

depend() {
	need portmap
	provide rstatd
}

start_post() {
	pgrep -n "${RC_SVCNAME}" > "${pidfile}"
}
